### ISSUE TITLE
Upgrade to OpenTracing 0.12.0

### ISSUE THREAD

**Issue by cwe1ss** [petabridge/Petabridge.Tracing.Zipkin#38]
Hi @Aaronontheweb ! 

We've just released [OpenTracing 0.12.0](https://github.com/opentracing/opentracing-csharp/releases/tag/0.12.0). 

fyi: Here's the diff for the upgrade in Jaeger: https://github.com/jaegertracing/jaeger-client-csharp/pull/63/files

Let me know if you have any questions!!

**Comment by Aaronontheweb** [comment]
@cwe1ss awesome, thanks! We'll look at upgrading straight away.
