### ISSUE TITLE
Calling ITracer.Inject with a NoOp span context causes cast exception

### ISSUE THREAD

**Issue by johnduhart** [petabridge/Petabridge.Tracing.Zipkin#56]
https://github.com/petabridge/Petabridge.Tracing.Zipkin/blob/dev/src/Petabridge.Tracing.Zipkin/ZipkinTracer.cs#L84

**Comment by Aaronontheweb** [comment]
Thanks for reporting this, @johnduhart - going to add this to my to-do list for the v0.4.0 release.
