### ISSUE TITLE
Support for "true" value on sampling state

### ISSUE THREAD

**Issue by johnduhart** [petabridge/Petabridge.Tracing.Zipkin#72]
From the [B3 Specification](https://github.com/openzipkin/b3-propagation#sampling-state-1).

> Note: Before this specification was written, some tracers propagated X-B3-Sampled as true or false as opposed to 1 or 0. While you shouldn't encode X-B3-Sampled as true or false, a lenient implementation may accept them.

[zipkin-ruby](https://github.com/openzipkin/zipkin-ruby) is still currently transmitting a sampled value using `true` or `false`, can support for this be added?

**Comment by Aaronontheweb** [comment]
@johnduhart yes it can!

**Comment by Aaronontheweb** [comment]
@johnduhart so to be clear on the implementation here - we can now read `true` for the X-B3-Sampled header, but we'll never encode the value as `true`. It'll always get encoded as `1` per the spec.
