### ISSUE TITLE
Open Kafka Producer for Reporting

### ISSUE THREAD

**Issue by mbrade** [petabridge/Petabridge.Tracing.Zipkin#93]
The options to define a Kafka connection to send reports via Kafka are not sufficient. We are using SASL_SSL and I'm missing a lot of options you need to set to configure a e.g. secured Kafka connection.
Would be nice to have an option to directly set an Producer so you keep this API independent from new Kafka features that need configuration on instantiation.

**Comment by Aaronontheweb** [comment]
@mbrade ok, so an overload to pass in your own Kafka producer? Can you expand on this?

**Comment by mbrade** [comment]
I'm sorry I'm no .net developer and the decision not to use zipkin in our company because of insufficient support for .net has already been taken.
