### ISSUE TITLE
FileLoadException when running Petabridge.Tracing.Zipkin in existing project that uses Akka 1.3.11

### ISSUE THREAD

**Issue by amichel** [petabridge/Petabridge.Tracing.Zipkin#94]
When running Petabridge.Tracing.Zipkin in existing project that uses Akka 1.3.11:

System.IO.FileLoadException: 'Could not load file or assembly 'Akka, Version=1.3.11.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'

**Comment by Aaronontheweb** [comment]
@amichel I think we're going to disable SN in the next release. 

https://github.com/petabridge/Petabridge.Tracing.Zipkin/pull/77 - going to disable this.
