### ISSUE TITLE
Request for preview release: Upgrade to Akka v1.4.0-beta1

### ISSUE THREAD

**Issue by Alksar** [petabridge/Petabridge.Tracing.Zipkin#96]
Recently akka was updated to [1.4.0-beta1 version](https://github.com/akkadotnet/akka.net/releases/tag/v1.4.0-beta1). It is no more depends on polyfills. Will be nice for this package too.

**Comment by Aaronontheweb** [comment]
@Alksar

We just updated to 1.3.16 - but we will do a release that targets v1.4.0-beta*.

I'm not sure how we'll do that exactly, but we'll look into it.

**Comment by Aaronontheweb** [comment]
This is available as part of https://github.com/petabridge/Petabridge.Tracing.Zipkin/releases/tag/0.6.0-beta1
